import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { getKindeServerSession } from "@kinde-oss/kinde-auth-nextjs/server";
import { redirect } from "next/navigation";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

	// const {getUser} = getKindeServerSession();
	// const user = await getUser();
	// if(user){
	// 	return redirect("/dashboard");
	// }
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
