import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { getKindeServerSession } from "@kinde-oss/kinde-auth-nextjs/server";
import { redirect } from "next/navigation";
import { NextSSRPlugin } from "@uploadthing/react/next-ssr-plugin";
import { extractRouterConfig } from "uploadthing/server";
import { ourFileRouter } from "./api/uploadthing/core";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

	// const {getUser} = getKindeServerSession();
	// const user = await getUser();
	// if(user){
	// 	return redirect("/dashboard");
	// }
  return (
    <html lang="en">
		<body className={inter.className}>
			<NextSSRPlugin
				routerConfig={extractRouterConfig(ourFileRouter)}
				/>
			{children}
		</body>
    </html>
  );
}
